## Data You will find company_data Dataset on the drive use it to solve the assignment.use Pandas to answer the following questions.

In [201]:
import pandas as pd
import numpy as np

file = pd.read_csv('company_data.csv')
df = pd.DataFrame(file)

### 1. Data Loading & Inspection Load the company_data.csv file. Print the first 10
rows and use a Pandas method to show the data types and check for missing
values in each column.

In [202]:
print(df.head(n=10))

   Employee_ID Employee_Name Department    Salary  Years_Experience  \
0          101      John Doe         IT   85000.0                 5
1          102    Jane Smith         HR   60000.0                 3
2          103   Ali Mansour      Sales       NaN                12
3          104      Sara Lee         IT   95000.0                 1
4          105     Ben Clark    Finance   70000.0                 8
5          106     Eva Green      Sales   55000.0                 4
6          107      Mona Ray         HR       NaN                 2
7          108      Leo King         IT  105000.0                10
8          109      Tom Cook    Finance   72000.0                 6
9          110     Anna Bell         IT   88000.0                 9

   Evaluation_Score   Bonus
0                88  5000.0
1                72  3000.0
2                95  7000.0
3                45     NaN
4                60  4000.0
5                82  2000.0
6                55     NaN
7                91  8000.0
8                78  4500.0
9                40  2500.0

In [203]:
print(df.isnull().sum())

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

In [204]:
print('printing summary statistics of the dataset')
print(df.describe())

printing summary statistics of the dataset
       Employee_ID         Salary  Years_Experience  Evaluation_Score  \
count     20.00000      18.000000         20.000000         20.000000
mean     110.50000   76555.555556          6.150000         72.050000
std        5.91608   18036.636644          3.910512         18.588267
min      101.00000   54000.000000          1.000000         30.000000
25%      105.75000   60500.000000          3.000000         63.750000
50%      110.50000   73500.000000          5.500000         75.500000
75%      115.25000   91000.000000          9.000000         85.750000
max      120.00000  110000.000000         15.000000         98.000000

             Bonus
count    18.000000
mean   4366.666667
std    2271.563338
min    1000.000000
25%    2625.000000
50%    4250.000000
75%    5750.000000
max    9000.000000

In [205]:
print('printing information about the dataset')
print(df.info())

printing information about the dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       20 non-null     int64
 1   Employee_Name     20 non-null     object
 2   Department        20 non-null     object
 3   Salary            18 non-null     float64
 4   Years_Experience  20 non-null     int64
 5   Evaluation_Score  20 non-null     int64
 6   Bonus             18 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.2+ KB
None

### 2. Handling Missing Values
- Fill the missing Salary values with the median salary of the entire
company.
-  Fill the missing Bonus values with 0.

In [206]:
df["Salary"].fillna(df["Salary"].median())
df["Bonus"].fillna(0)

df.isnull().sum()

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

### Data Cleaning: The Employee_Name column is in the format "FirstName
LastName". Split this column into two new columns: First_Name and Last_Name,
then delete the original Employee_Name column.

In [207]:
# Split the Employee_Name column into First_Name and Last_Name
df[['First_Name', 'Last_Name']] = df['Employee_Name'].str.split(' ', expand=True)

# Delete the original column
df.drop(columns=['Employee_Name'], inplace=True)

In [208]:
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,IT,85000.0,5,88,5000.0,John,Doe
1,102,HR,60000.0,3,72,3000.0,Jane,Smith
2,103,Sales,NaN,12,95,7000.0,Ali,Mansour
3,104,IT,95000.0,1,45,NaN,Sara,Lee
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark

### filtering :Create a new DataFrame called Senior_IT that contains only employees
from the 'IT' department who have more than 8 years of experience.

In [209]:
Senior_IT = df.query('Department == "IT" and Salary > 70000')
print(Senior_IT)

    Employee_ID Department    Salary  Years_Experience  Evaluation_Score  \
0           101         IT   85000.0                 5                88
3           104         IT   95000.0                 1                45
7           108         IT  105000.0                10                91
9           110         IT   88000.0                 9                40
12          113         IT   92000.0                11                77
15          116         IT  110000.0                15                98
18          119         IT   98000.0                 9                81

     Bonus First_Name Last_Name
0   5000.0       John       Doe
3      NaN       Sara       Lee
7   8000.0        Leo      King
9   2500.0       Anna      Bell
12  6000.0       Will     Smith
15  9000.0      Bruce     Wayne
18  6500.0      Barry     Allen

### 5. Performance Mapping Create a new column called Performance_Level based on
the Evaluation_Score (1-100):
• Score > 80: "High"
• Score 50-80: "Medium"
• Score < 50: "Low"

In [210]:
df["Performance_Level"] = [
    "High" if x > 80 else "Medium" if x >= 50 else "Low"
    for x in df["Evaluation_Score"]
]

In [211]:
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,85000.0,5,88,5000.0,John,Doe,High
1,102,HR,60000.0,3,72,3000.0,Jane,Smith,Medium
2,103,Sales,NaN,12,95,7000.0,Ali,Mansour,High
3,104,IT,95000.0,1,45,NaN,Sara,Lee,Low
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark,Medium

### . Calculate the total salary expense and the average evaluation score for each
Department.

In [212]:
# calculate the totle salery
totlal_slary = df.groupby("Department")["Salary"].sum()
print(totlal_slary)

# average evualution
average = df.groupby("Department")["Evaluation_Score"].mean()
print(average)

Department
Finance    294000.0
HR         185000.0
IT         673000.0
Sales      226000.0
Name: Salary, dtype: float64
Department
Finance    74.250000
HR         71.500000
IT         74.285714
Sales      67.600000
Name: Evaluation_Score, dtype: float64

In [213]:

df_sorted = df.sort_values("Salary", ascending=False)

# أول 5 صفوف
top5 = df_sorted.head(5)

print(top5[["First_Name", "Salary"]])

   First_Name    Salary
15      Bruce  110000.0
7         Leo  105000.0
18      Barry   98000.0
3        Sara   95000.0
12       Will   92000.0

### . The company is giving a 10% raise to everyone in the 'Sales' department. Update
the Salary column for those employees only.

In [214]:
### . The company is giving a 10% raise to everyone in the 'Sales' department. Update

df["Salary"] = df["Salary"] * 1.10
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,93500.0,5,88,5000.0,John,Doe,High
1,102,HR,66000.0,3,72,3000.0,Jane,Smith,Medium
2,103,Sales,NaN,12,95,7000.0,Ali,Mansour,High
3,104,IT,104500.0,1,45,NaN,Sara,Lee,Low
4,105,Finance,77000.0,8,60,4000.0,Ben,Clark,Medium

### 9. Exporting Results Save the final, cleaned, and updated DataFrame to a new Excel
or CSV file named final_employee_report.csv.

In [215]:
final_employee_report = df.to_csv('final_employee_report.csv')